services:
  app:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    networks:
      - chain-services
      - wheelz-app
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync+restart
        - path: .env
          target: /app/.env
          action: sync+restart
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
  mongo:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
      - 'MONGODB_USER=wheelz'
      - 'MONGODB_PASSWORD=root'
      - 'MONGODB_DATABASE=${CHAIN_DATABASE_NAME}'
    volumes:
      - 'mongodb_data:/data/db'
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init.sh:ro

    networks:
      - chain-services
networks:
  chain-services:
  wheelz-app:
    external: true
volumes:
  mongodb_data:
