services:
  chain_state_db:
    image: postgres:17.2
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${CHAIN_STATE_DB_NAME}
      POSTGRES_USER: ${CHAIN_STATE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CHAIN_STATE_DB_PASSWORD}
    volumes:
      - wheelz-chain-state-service-local-volume:/var/lib/postgresql/data
    networks:
      - chain-services
  chain_api:
    build:
      context: .
      target: development
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - chain-services
      - wheelz-app
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync+restart
        - path: .env
          target: /app/.env
          action: sync+restart
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild

networks:
  chain-services:
  wheelz-app:
    external: true
volumes:
  mongodb_data:
  wheelz-chain-state-service-local-volume:
